### ISSUE TITLE
OSError: [Errno30]

### ISSUE THREAD

**Issue by davidjquispe** [dib-lab/dammit#150]
Hello, 

I have a problem with the dammit pipeline at the beginning. Thanks for the help you can give me.

-David

**Here is my code:**
dammit annotate Trinity.fasta

**This is the error message that I received:**

#dammit
##a tool for easy de novo transcriptome annotation
by Camille Scott
**v1.0rc2**, 2018
Traceback (most recent call last):
  File "/home/jgarcia/dquispe/miniconda3/envs/dammit/bin/dammit", line 9, in <module>
    sys.exit(app.DammitApp(arg_src=sys.argv[1:]).run())
  File "/home/jgarcia/dquispe/miniconda3/envs/dammit/lib/python3.6/site-packages/dammit/app.py", line 45, in run
    return self.args.func()
  File "/home/jgarcia/dquispe/miniconda3/envs/dammit/lib/python3.6/site-packages/dammit/app.py", line 289, in handle_annotate
    log.start_logging()
  File "/home/jgarcia/dquispe/miniconda3/envs/dammit/lib/python3.6/site-packages/dammit/log.py", line 39, in run
    logging.basicConfig(level=logging.DEBUG, **config)
  File "/home/jgarcia/dquispe/miniconda3/envs/dammit/lib/python3.6/logging/__init__.py", line 1808, in basicConfig
    h = FileHandler(filename, mode)
  File "/home/jgarcia/dquispe/miniconda3/envs/dammit/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/jgarcia/dquispe/miniconda3/envs/dammit/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 30] Read-only file system: '/home/jgarcia/dquispe/.dammit/log/dammit-all.log'

**Comment by camillescott** [comment]
Hi there, sorry for the long wait. It looks like you don't have write access to the log directory. Is this on a shared system?

Also, I recommend upgrading to 1.2, which is on biocionda.
